server:
  port: 10001
  servlet:
    context-path: /duid-service

spring:
  threads:
    virtual:
      enabled: true

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://192.168.0.206:5432/postgres
  username: postgres
  password: password
  max-pool-size: 40
  connection-test-query: "SELECT 1"
  pool-name: springHikariCP

