server:
  port: 10002
  servlet:
    context-path: /duid-service

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: duid-service
  kafka:
    producer:
      bootstrap-servers: 192.168.0.206:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10012
  security:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: dev
  threads:
    virtual:
      enabled: true
  application:
    name: duid-service
  kafka:
    producer:
      bootstrap-servers: 192.168.0.206:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  servlet:
    context-path: /duid-service
  port: 10002

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10012
  security:
    enabled: false


